//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace FTTEST.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AVTC_webserviceSoap", Namespace="http://tempuri.org/")]
    public partial class AVTC_webservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_product_hOperationCompleted;
        
        private System.Threading.SendOrPostCallback hello_wordOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_EM_BUOperationCompleted;
        
        private System.Threading.SendOrPostCallback SD_WBEROperationCompleted;
        
        private System.Threading.SendOrPostCallback SD_STCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback SD_TVDROperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_DC_CHECKOperationCompleted;
        
        private System.Threading.SendOrPostCallback QRY_DC_CHECKOperationCompleted;
        
        private System.Threading.SendOrPostCallback QRY_EMP_IDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CHK_MES_ROUTEOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_MES_STATIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_MES_PART_LINKOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_DIXIE_MACOperationCompleted;
        
        private System.Threading.SendOrPostCallback UPD_DIXIE_MACOperationCompleted;
        
        private System.Threading.SendOrPostCallback QRY_sn_kppnOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_8L_WOOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_check_3TOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_ST_FILE_CONFIGOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_ST_FILEOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_CHK_MOUSE_LABEL_RESULTOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_AOI_PATHOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_MV_TEST_LOGOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_TEST_INFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_TEST_INFOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AVTC_webservice() {
            this.Url = global::FTTEST.Properties.Settings.Default.FTTEST_WebReference_AVTC_webservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_product_hCompletedEventHandler get_product_hCompleted;
        
        /// <remarks/>
        public event hello_wordCompletedEventHandler hello_wordCompleted;
        
        /// <remarks/>
        public event INS_EM_BUCompletedEventHandler INS_EM_BUCompleted;
        
        /// <remarks/>
        public event SD_WBERCompletedEventHandler SD_WBERCompleted;
        
        /// <remarks/>
        public event SD_STCKCompletedEventHandler SD_STCKCompleted;
        
        /// <remarks/>
        public event SD_TVDRCompletedEventHandler SD_TVDRCompleted;
        
        /// <remarks/>
        public event INS_DC_CHECKCompletedEventHandler INS_DC_CHECKCompleted;
        
        /// <remarks/>
        public event QRY_DC_CHECKCompletedEventHandler QRY_DC_CHECKCompleted;
        
        /// <remarks/>
        public event QRY_EMP_IDCompletedEventHandler QRY_EMP_IDCompleted;
        
        /// <remarks/>
        public event CHK_MES_ROUTECompletedEventHandler CHK_MES_ROUTECompleted;
        
        /// <remarks/>
        public event INS_MES_STATIONCompletedEventHandler INS_MES_STATIONCompleted;
        
        /// <remarks/>
        public event INS_MES_PART_LINKCompletedEventHandler INS_MES_PART_LINKCompleted;
        
        /// <remarks/>
        public event GET_DIXIE_MACCompletedEventHandler GET_DIXIE_MACCompleted;
        
        /// <remarks/>
        public event UPD_DIXIE_MACCompletedEventHandler UPD_DIXIE_MACCompleted;
        
        /// <remarks/>
        public event QRY_sn_kppnCompletedEventHandler QRY_sn_kppnCompleted;
        
        /// <remarks/>
        public event get_8L_WOCompletedEventHandler get_8L_WOCompleted;
        
        /// <remarks/>
        public event INS_check_3TCompletedEventHandler INS_check_3TCompleted;
        
        /// <remarks/>
        public event GET_ST_FILE_CONFIGCompletedEventHandler GET_ST_FILE_CONFIGCompleted;
        
        /// <remarks/>
        public event INS_ST_FILECompletedEventHandler INS_ST_FILECompleted;
        
        /// <remarks/>
        public event INS_CHK_MOUSE_LABEL_RESULTCompletedEventHandler INS_CHK_MOUSE_LABEL_RESULTCompleted;
        
        /// <remarks/>
        public event INS_AOI_PATHCompletedEventHandler INS_AOI_PATHCompleted;
        
        /// <remarks/>
        public event INS_MV_TEST_LOGCompletedEventHandler INS_MV_TEST_LOGCompleted;
        
        /// <remarks/>
        public event INS_TEST_INFOCompletedEventHandler INS_TEST_INFOCompleted;
        
        /// <remarks/>
        public event GET_TEST_INFOCompletedEventHandler GET_TEST_INFOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_product_h", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_product_h(string sn) {
            object[] results = this.Invoke("get_product_h", new object[] {
                        sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_product_hAsync(string sn) {
            this.get_product_hAsync(sn, null);
        }
        
        /// <remarks/>
        public void get_product_hAsync(string sn, object userState) {
            if ((this.get_product_hOperationCompleted == null)) {
                this.get_product_hOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_product_hOperationCompleted);
            }
            this.InvokeAsync("get_product_h", new object[] {
                        sn}, this.get_product_hOperationCompleted, userState);
        }
        
        private void Onget_product_hOperationCompleted(object arg) {
            if ((this.get_product_hCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_product_hCompleted(this, new get_product_hCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/hello_word", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string hello_word(string sn) {
            object[] results = this.Invoke("hello_word", new object[] {
                        sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hello_wordAsync(string sn) {
            this.hello_wordAsync(sn, null);
        }
        
        /// <remarks/>
        public void hello_wordAsync(string sn, object userState) {
            if ((this.hello_wordOperationCompleted == null)) {
                this.hello_wordOperationCompleted = new System.Threading.SendOrPostCallback(this.Onhello_wordOperationCompleted);
            }
            this.InvokeAsync("hello_word", new object[] {
                        sn}, this.hello_wordOperationCompleted, userState);
        }
        
        private void Onhello_wordOperationCompleted(object arg) {
            if ((this.hello_wordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hello_wordCompleted(this, new hello_wordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_EM_BU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_EM_BU(string x_json) {
            object[] results = this.Invoke("INS_EM_BU", new object[] {
                        x_json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_EM_BUAsync(string x_json) {
            this.INS_EM_BUAsync(x_json, null);
        }
        
        /// <remarks/>
        public void INS_EM_BUAsync(string x_json, object userState) {
            if ((this.INS_EM_BUOperationCompleted == null)) {
                this.INS_EM_BUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_EM_BUOperationCompleted);
            }
            this.InvokeAsync("INS_EM_BU", new object[] {
                        x_json}, this.INS_EM_BUOperationCompleted, userState);
        }
        
        private void OnINS_EM_BUOperationCompleted(object arg) {
            if ((this.INS_EM_BUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_EM_BUCompleted(this, new INS_EM_BUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SD_WBER", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SD_WBER(string x_meseid, string x_sn, string x_user, string pf, string x_comment) {
            object[] results = this.Invoke("SD_WBER", new object[] {
                        x_meseid,
                        x_sn,
                        x_user,
                        pf,
                        x_comment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SD_WBERAsync(string x_meseid, string x_sn, string x_user, string pf, string x_comment) {
            this.SD_WBERAsync(x_meseid, x_sn, x_user, pf, x_comment, null);
        }
        
        /// <remarks/>
        public void SD_WBERAsync(string x_meseid, string x_sn, string x_user, string pf, string x_comment, object userState) {
            if ((this.SD_WBEROperationCompleted == null)) {
                this.SD_WBEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSD_WBEROperationCompleted);
            }
            this.InvokeAsync("SD_WBER", new object[] {
                        x_meseid,
                        x_sn,
                        x_user,
                        pf,
                        x_comment}, this.SD_WBEROperationCompleted, userState);
        }
        
        private void OnSD_WBEROperationCompleted(object arg) {
            if ((this.SD_WBERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SD_WBERCompleted(this, new SD_WBERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SD_STCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SD_STCK(string x_meseid, string x_sn, string x_user) {
            object[] results = this.Invoke("SD_STCK", new object[] {
                        x_meseid,
                        x_sn,
                        x_user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SD_STCKAsync(string x_meseid, string x_sn, string x_user) {
            this.SD_STCKAsync(x_meseid, x_sn, x_user, null);
        }
        
        /// <remarks/>
        public void SD_STCKAsync(string x_meseid, string x_sn, string x_user, object userState) {
            if ((this.SD_STCKOperationCompleted == null)) {
                this.SD_STCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSD_STCKOperationCompleted);
            }
            this.InvokeAsync("SD_STCK", new object[] {
                        x_meseid,
                        x_sn,
                        x_user}, this.SD_STCKOperationCompleted, userState);
        }
        
        private void OnSD_STCKOperationCompleted(object arg) {
            if ((this.SD_STCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SD_STCKCompleted(this, new SD_STCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SD_TVDR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SD_TVDR(string x_meseid, string x_sn, string CD, string TYPE, string DV_ID, string x_user, string x_comment) {
            object[] results = this.Invoke("SD_TVDR", new object[] {
                        x_meseid,
                        x_sn,
                        CD,
                        TYPE,
                        DV_ID,
                        x_user,
                        x_comment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SD_TVDRAsync(string x_meseid, string x_sn, string CD, string TYPE, string DV_ID, string x_user, string x_comment) {
            this.SD_TVDRAsync(x_meseid, x_sn, CD, TYPE, DV_ID, x_user, x_comment, null);
        }
        
        /// <remarks/>
        public void SD_TVDRAsync(string x_meseid, string x_sn, string CD, string TYPE, string DV_ID, string x_user, string x_comment, object userState) {
            if ((this.SD_TVDROperationCompleted == null)) {
                this.SD_TVDROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSD_TVDROperationCompleted);
            }
            this.InvokeAsync("SD_TVDR", new object[] {
                        x_meseid,
                        x_sn,
                        CD,
                        TYPE,
                        DV_ID,
                        x_user,
                        x_comment}, this.SD_TVDROperationCompleted, userState);
        }
        
        private void OnSD_TVDROperationCompleted(object arg) {
            if ((this.SD_TVDRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SD_TVDRCompleted(this, new SD_TVDRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_DC_CHECK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_DC_CHECK(string x_trid, string x_workorder, string x_pn, string x_op, string x_info, string x_okng, string x_eventtime, string x_st_code) {
            object[] results = this.Invoke("INS_DC_CHECK", new object[] {
                        x_trid,
                        x_workorder,
                        x_pn,
                        x_op,
                        x_info,
                        x_okng,
                        x_eventtime,
                        x_st_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_DC_CHECKAsync(string x_trid, string x_workorder, string x_pn, string x_op, string x_info, string x_okng, string x_eventtime, string x_st_code) {
            this.INS_DC_CHECKAsync(x_trid, x_workorder, x_pn, x_op, x_info, x_okng, x_eventtime, x_st_code, null);
        }
        
        /// <remarks/>
        public void INS_DC_CHECKAsync(string x_trid, string x_workorder, string x_pn, string x_op, string x_info, string x_okng, string x_eventtime, string x_st_code, object userState) {
            if ((this.INS_DC_CHECKOperationCompleted == null)) {
                this.INS_DC_CHECKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_DC_CHECKOperationCompleted);
            }
            this.InvokeAsync("INS_DC_CHECK", new object[] {
                        x_trid,
                        x_workorder,
                        x_pn,
                        x_op,
                        x_info,
                        x_okng,
                        x_eventtime,
                        x_st_code}, this.INS_DC_CHECKOperationCompleted, userState);
        }
        
        private void OnINS_DC_CHECKOperationCompleted(object arg) {
            if ((this.INS_DC_CHECKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_DC_CHECKCompleted(this, new INS_DC_CHECKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QRY_DC_CHECK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QRY_DC_CHECK(string con) {
            object[] results = this.Invoke("QRY_DC_CHECK", new object[] {
                        con});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QRY_DC_CHECKAsync(string con) {
            this.QRY_DC_CHECKAsync(con, null);
        }
        
        /// <remarks/>
        public void QRY_DC_CHECKAsync(string con, object userState) {
            if ((this.QRY_DC_CHECKOperationCompleted == null)) {
                this.QRY_DC_CHECKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQRY_DC_CHECKOperationCompleted);
            }
            this.InvokeAsync("QRY_DC_CHECK", new object[] {
                        con}, this.QRY_DC_CHECKOperationCompleted, userState);
        }
        
        private void OnQRY_DC_CHECKOperationCompleted(object arg) {
            if ((this.QRY_DC_CHECKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QRY_DC_CHECKCompleted(this, new QRY_DC_CHECKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QRY_EMP_ID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QRY_EMP_ID(string card_no) {
            object[] results = this.Invoke("QRY_EMP_ID", new object[] {
                        card_no});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QRY_EMP_IDAsync(string card_no) {
            this.QRY_EMP_IDAsync(card_no, null);
        }
        
        /// <remarks/>
        public void QRY_EMP_IDAsync(string card_no, object userState) {
            if ((this.QRY_EMP_IDOperationCompleted == null)) {
                this.QRY_EMP_IDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQRY_EMP_IDOperationCompleted);
            }
            this.InvokeAsync("QRY_EMP_ID", new object[] {
                        card_no}, this.QRY_EMP_IDOperationCompleted, userState);
        }
        
        private void OnQRY_EMP_IDOperationCompleted(object arg) {
            if ((this.QRY_EMP_IDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QRY_EMP_IDCompleted(this, new QRY_EMP_IDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CHK_MES_ROUTE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CHK_MES_ROUTE(string x_ST_ID, string x_SN) {
            object[] results = this.Invoke("CHK_MES_ROUTE", new object[] {
                        x_ST_ID,
                        x_SN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CHK_MES_ROUTEAsync(string x_ST_ID, string x_SN) {
            this.CHK_MES_ROUTEAsync(x_ST_ID, x_SN, null);
        }
        
        /// <remarks/>
        public void CHK_MES_ROUTEAsync(string x_ST_ID, string x_SN, object userState) {
            if ((this.CHK_MES_ROUTEOperationCompleted == null)) {
                this.CHK_MES_ROUTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCHK_MES_ROUTEOperationCompleted);
            }
            this.InvokeAsync("CHK_MES_ROUTE", new object[] {
                        x_ST_ID,
                        x_SN}, this.CHK_MES_ROUTEOperationCompleted, userState);
        }
        
        private void OnCHK_MES_ROUTEOperationCompleted(object arg) {
            if ((this.CHK_MES_ROUTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CHK_MES_ROUTECompleted(this, new CHK_MES_ROUTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_MES_STATION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_MES_STATION(string x_ST_ID, string x_SN, string x_user, string x_defect) {
            object[] results = this.Invoke("INS_MES_STATION", new object[] {
                        x_ST_ID,
                        x_SN,
                        x_user,
                        x_defect});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_MES_STATIONAsync(string x_ST_ID, string x_SN, string x_user, string x_defect) {
            this.INS_MES_STATIONAsync(x_ST_ID, x_SN, x_user, x_defect, null);
        }
        
        /// <remarks/>
        public void INS_MES_STATIONAsync(string x_ST_ID, string x_SN, string x_user, string x_defect, object userState) {
            if ((this.INS_MES_STATIONOperationCompleted == null)) {
                this.INS_MES_STATIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_MES_STATIONOperationCompleted);
            }
            this.InvokeAsync("INS_MES_STATION", new object[] {
                        x_ST_ID,
                        x_SN,
                        x_user,
                        x_defect}, this.INS_MES_STATIONOperationCompleted, userState);
        }
        
        private void OnINS_MES_STATIONOperationCompleted(object arg) {
            if ((this.INS_MES_STATIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_MES_STATIONCompleted(this, new INS_MES_STATIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_MES_PART_LINK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_MES_PART_LINK(string x_ST_ID, string x_SN, string x_PART_NO, string x_PART_SN) {
            object[] results = this.Invoke("INS_MES_PART_LINK", new object[] {
                        x_ST_ID,
                        x_SN,
                        x_PART_NO,
                        x_PART_SN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_MES_PART_LINKAsync(string x_ST_ID, string x_SN, string x_PART_NO, string x_PART_SN) {
            this.INS_MES_PART_LINKAsync(x_ST_ID, x_SN, x_PART_NO, x_PART_SN, null);
        }
        
        /// <remarks/>
        public void INS_MES_PART_LINKAsync(string x_ST_ID, string x_SN, string x_PART_NO, string x_PART_SN, object userState) {
            if ((this.INS_MES_PART_LINKOperationCompleted == null)) {
                this.INS_MES_PART_LINKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_MES_PART_LINKOperationCompleted);
            }
            this.InvokeAsync("INS_MES_PART_LINK", new object[] {
                        x_ST_ID,
                        x_SN,
                        x_PART_NO,
                        x_PART_SN}, this.INS_MES_PART_LINKOperationCompleted, userState);
        }
        
        private void OnINS_MES_PART_LINKOperationCompleted(object arg) {
            if ((this.INS_MES_PART_LINKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_MES_PART_LINKCompleted(this, new INS_MES_PART_LINKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_DIXIE_MAC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GET_DIXIE_MAC(string sn, string use_mode) {
            object[] results = this.Invoke("GET_DIXIE_MAC", new object[] {
                        sn,
                        use_mode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GET_DIXIE_MACAsync(string sn, string use_mode) {
            this.GET_DIXIE_MACAsync(sn, use_mode, null);
        }
        
        /// <remarks/>
        public void GET_DIXIE_MACAsync(string sn, string use_mode, object userState) {
            if ((this.GET_DIXIE_MACOperationCompleted == null)) {
                this.GET_DIXIE_MACOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_DIXIE_MACOperationCompleted);
            }
            this.InvokeAsync("GET_DIXIE_MAC", new object[] {
                        sn,
                        use_mode}, this.GET_DIXIE_MACOperationCompleted, userState);
        }
        
        private void OnGET_DIXIE_MACOperationCompleted(object arg) {
            if ((this.GET_DIXIE_MACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_DIXIE_MACCompleted(this, new GET_DIXIE_MACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPD_DIXIE_MAC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UPD_DIXIE_MAC(string sn, string mac, string use_mode) {
            object[] results = this.Invoke("UPD_DIXIE_MAC", new object[] {
                        sn,
                        mac,
                        use_mode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UPD_DIXIE_MACAsync(string sn, string mac, string use_mode) {
            this.UPD_DIXIE_MACAsync(sn, mac, use_mode, null);
        }
        
        /// <remarks/>
        public void UPD_DIXIE_MACAsync(string sn, string mac, string use_mode, object userState) {
            if ((this.UPD_DIXIE_MACOperationCompleted == null)) {
                this.UPD_DIXIE_MACOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPD_DIXIE_MACOperationCompleted);
            }
            this.InvokeAsync("UPD_DIXIE_MAC", new object[] {
                        sn,
                        mac,
                        use_mode}, this.UPD_DIXIE_MACOperationCompleted, userState);
        }
        
        private void OnUPD_DIXIE_MACOperationCompleted(object arg) {
            if ((this.UPD_DIXIE_MACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPD_DIXIE_MACCompleted(this, new UPD_DIXIE_MACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QRY_sn_kppn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QRY_sn_kppn(string x_sn) {
            object[] results = this.Invoke("QRY_sn_kppn", new object[] {
                        x_sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QRY_sn_kppnAsync(string x_sn) {
            this.QRY_sn_kppnAsync(x_sn, null);
        }
        
        /// <remarks/>
        public void QRY_sn_kppnAsync(string x_sn, object userState) {
            if ((this.QRY_sn_kppnOperationCompleted == null)) {
                this.QRY_sn_kppnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQRY_sn_kppnOperationCompleted);
            }
            this.InvokeAsync("QRY_sn_kppn", new object[] {
                        x_sn}, this.QRY_sn_kppnOperationCompleted, userState);
        }
        
        private void OnQRY_sn_kppnOperationCompleted(object arg) {
            if ((this.QRY_sn_kppnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QRY_sn_kppnCompleted(this, new QRY_sn_kppnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_8L_WO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_8L_WO(string sn) {
            object[] results = this.Invoke("get_8L_WO", new object[] {
                        sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_8L_WOAsync(string sn) {
            this.get_8L_WOAsync(sn, null);
        }
        
        /// <remarks/>
        public void get_8L_WOAsync(string sn, object userState) {
            if ((this.get_8L_WOOperationCompleted == null)) {
                this.get_8L_WOOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_8L_WOOperationCompleted);
            }
            this.InvokeAsync("get_8L_WO", new object[] {
                        sn}, this.get_8L_WOOperationCompleted, userState);
        }
        
        private void Onget_8L_WOOperationCompleted(object arg) {
            if ((this.get_8L_WOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_8L_WOCompleted(this, new get_8L_WOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_check_3T", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_check_3T(string x_sn, string x_ST_ID, string x_result, string x_error_code, string x_error_contect, string user_id) {
            object[] results = this.Invoke("INS_check_3T", new object[] {
                        x_sn,
                        x_ST_ID,
                        x_result,
                        x_error_code,
                        x_error_contect,
                        user_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_check_3TAsync(string x_sn, string x_ST_ID, string x_result, string x_error_code, string x_error_contect, string user_id) {
            this.INS_check_3TAsync(x_sn, x_ST_ID, x_result, x_error_code, x_error_contect, user_id, null);
        }
        
        /// <remarks/>
        public void INS_check_3TAsync(string x_sn, string x_ST_ID, string x_result, string x_error_code, string x_error_contect, string user_id, object userState) {
            if ((this.INS_check_3TOperationCompleted == null)) {
                this.INS_check_3TOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_check_3TOperationCompleted);
            }
            this.InvokeAsync("INS_check_3T", new object[] {
                        x_sn,
                        x_ST_ID,
                        x_result,
                        x_error_code,
                        x_error_contect,
                        user_id}, this.INS_check_3TOperationCompleted, userState);
        }
        
        private void OnINS_check_3TOperationCompleted(object arg) {
            if ((this.INS_check_3TCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_check_3TCompleted(this, new INS_check_3TCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_ST_FILE_CONFIG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GET_ST_FILE_CONFIG(string x_sn, string x_ST_ID) {
            object[] results = this.Invoke("GET_ST_FILE_CONFIG", new object[] {
                        x_sn,
                        x_ST_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GET_ST_FILE_CONFIGAsync(string x_sn, string x_ST_ID) {
            this.GET_ST_FILE_CONFIGAsync(x_sn, x_ST_ID, null);
        }
        
        /// <remarks/>
        public void GET_ST_FILE_CONFIGAsync(string x_sn, string x_ST_ID, object userState) {
            if ((this.GET_ST_FILE_CONFIGOperationCompleted == null)) {
                this.GET_ST_FILE_CONFIGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_ST_FILE_CONFIGOperationCompleted);
            }
            this.InvokeAsync("GET_ST_FILE_CONFIG", new object[] {
                        x_sn,
                        x_ST_ID}, this.GET_ST_FILE_CONFIGOperationCompleted, userState);
        }
        
        private void OnGET_ST_FILE_CONFIGOperationCompleted(object arg) {
            if ((this.GET_ST_FILE_CONFIGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_ST_FILE_CONFIGCompleted(this, new GET_ST_FILE_CONFIGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_ST_FILE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_ST_FILE(string x_sn, string x_ST_ID, string x_result, string x_file_name, string user_id) {
            object[] results = this.Invoke("INS_ST_FILE", new object[] {
                        x_sn,
                        x_ST_ID,
                        x_result,
                        x_file_name,
                        user_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_ST_FILEAsync(string x_sn, string x_ST_ID, string x_result, string x_file_name, string user_id) {
            this.INS_ST_FILEAsync(x_sn, x_ST_ID, x_result, x_file_name, user_id, null);
        }
        
        /// <remarks/>
        public void INS_ST_FILEAsync(string x_sn, string x_ST_ID, string x_result, string x_file_name, string user_id, object userState) {
            if ((this.INS_ST_FILEOperationCompleted == null)) {
                this.INS_ST_FILEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_ST_FILEOperationCompleted);
            }
            this.InvokeAsync("INS_ST_FILE", new object[] {
                        x_sn,
                        x_ST_ID,
                        x_result,
                        x_file_name,
                        user_id}, this.INS_ST_FILEOperationCompleted, userState);
        }
        
        private void OnINS_ST_FILEOperationCompleted(object arg) {
            if ((this.INS_ST_FILECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_ST_FILECompleted(this, new INS_ST_FILECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_CHK_MOUSE_LABEL_RESULT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_CHK_MOUSE_LABEL_RESULT(string x_sn, string x_version) {
            object[] results = this.Invoke("INS_CHK_MOUSE_LABEL_RESULT", new object[] {
                        x_sn,
                        x_version});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_CHK_MOUSE_LABEL_RESULTAsync(string x_sn, string x_version) {
            this.INS_CHK_MOUSE_LABEL_RESULTAsync(x_sn, x_version, null);
        }
        
        /// <remarks/>
        public void INS_CHK_MOUSE_LABEL_RESULTAsync(string x_sn, string x_version, object userState) {
            if ((this.INS_CHK_MOUSE_LABEL_RESULTOperationCompleted == null)) {
                this.INS_CHK_MOUSE_LABEL_RESULTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_CHK_MOUSE_LABEL_RESULTOperationCompleted);
            }
            this.InvokeAsync("INS_CHK_MOUSE_LABEL_RESULT", new object[] {
                        x_sn,
                        x_version}, this.INS_CHK_MOUSE_LABEL_RESULTOperationCompleted, userState);
        }
        
        private void OnINS_CHK_MOUSE_LABEL_RESULTOperationCompleted(object arg) {
            if ((this.INS_CHK_MOUSE_LABEL_RESULTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_CHK_MOUSE_LABEL_RESULTCompleted(this, new INS_CHK_MOUSE_LABEL_RESULTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_AOI_PATH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_AOI_PATH(string x_sn, string x_type, string x_path, string x_user) {
            object[] results = this.Invoke("INS_AOI_PATH", new object[] {
                        x_sn,
                        x_type,
                        x_path,
                        x_user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_AOI_PATHAsync(string x_sn, string x_type, string x_path, string x_user) {
            this.INS_AOI_PATHAsync(x_sn, x_type, x_path, x_user, null);
        }
        
        /// <remarks/>
        public void INS_AOI_PATHAsync(string x_sn, string x_type, string x_path, string x_user, object userState) {
            if ((this.INS_AOI_PATHOperationCompleted == null)) {
                this.INS_AOI_PATHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_AOI_PATHOperationCompleted);
            }
            this.InvokeAsync("INS_AOI_PATH", new object[] {
                        x_sn,
                        x_type,
                        x_path,
                        x_user}, this.INS_AOI_PATHOperationCompleted, userState);
        }
        
        private void OnINS_AOI_PATHOperationCompleted(object arg) {
            if ((this.INS_AOI_PATHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_AOI_PATHCompleted(this, new INS_AOI_PATHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_MV_TEST_LOG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_MV_TEST_LOG(string Model, string Line, string Station, string SeqNum, string Status, string TestStartTime, string Data1, string Data2, string Data3) {
            object[] results = this.Invoke("INS_MV_TEST_LOG", new object[] {
                        Model,
                        Line,
                        Station,
                        SeqNum,
                        Status,
                        TestStartTime,
                        Data1,
                        Data2,
                        Data3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_MV_TEST_LOGAsync(string Model, string Line, string Station, string SeqNum, string Status, string TestStartTime, string Data1, string Data2, string Data3) {
            this.INS_MV_TEST_LOGAsync(Model, Line, Station, SeqNum, Status, TestStartTime, Data1, Data2, Data3, null);
        }
        
        /// <remarks/>
        public void INS_MV_TEST_LOGAsync(string Model, string Line, string Station, string SeqNum, string Status, string TestStartTime, string Data1, string Data2, string Data3, object userState) {
            if ((this.INS_MV_TEST_LOGOperationCompleted == null)) {
                this.INS_MV_TEST_LOGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_MV_TEST_LOGOperationCompleted);
            }
            this.InvokeAsync("INS_MV_TEST_LOG", new object[] {
                        Model,
                        Line,
                        Station,
                        SeqNum,
                        Status,
                        TestStartTime,
                        Data1,
                        Data2,
                        Data3}, this.INS_MV_TEST_LOGOperationCompleted, userState);
        }
        
        private void OnINS_MV_TEST_LOGOperationCompleted(object arg) {
            if ((this.INS_MV_TEST_LOGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_MV_TEST_LOGCompleted(this, new INS_MV_TEST_LOGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_TEST_INFO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_TEST_INFO(string x_sn, string x_model, string x_stage, string x_json) {
            object[] results = this.Invoke("INS_TEST_INFO", new object[] {
                        x_sn,
                        x_model,
                        x_stage,
                        x_json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_TEST_INFOAsync(string x_sn, string x_model, string x_stage, string x_json) {
            this.INS_TEST_INFOAsync(x_sn, x_model, x_stage, x_json, null);
        }
        
        /// <remarks/>
        public void INS_TEST_INFOAsync(string x_sn, string x_model, string x_stage, string x_json, object userState) {
            if ((this.INS_TEST_INFOOperationCompleted == null)) {
                this.INS_TEST_INFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_TEST_INFOOperationCompleted);
            }
            this.InvokeAsync("INS_TEST_INFO", new object[] {
                        x_sn,
                        x_model,
                        x_stage,
                        x_json}, this.INS_TEST_INFOOperationCompleted, userState);
        }
        
        private void OnINS_TEST_INFOOperationCompleted(object arg) {
            if ((this.INS_TEST_INFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_TEST_INFOCompleted(this, new INS_TEST_INFOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_TEST_INFO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GET_TEST_INFO(string x_sn) {
            object[] results = this.Invoke("GET_TEST_INFO", new object[] {
                        x_sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GET_TEST_INFOAsync(string x_sn) {
            this.GET_TEST_INFOAsync(x_sn, null);
        }
        
        /// <remarks/>
        public void GET_TEST_INFOAsync(string x_sn, object userState) {
            if ((this.GET_TEST_INFOOperationCompleted == null)) {
                this.GET_TEST_INFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_TEST_INFOOperationCompleted);
            }
            this.InvokeAsync("GET_TEST_INFO", new object[] {
                        x_sn}, this.GET_TEST_INFOOperationCompleted, userState);
        }
        
        private void OnGET_TEST_INFOOperationCompleted(object arg) {
            if ((this.GET_TEST_INFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_TEST_INFOCompleted(this, new GET_TEST_INFOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void get_product_hCompletedEventHandler(object sender, get_product_hCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_product_hCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_product_hCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void hello_wordCompletedEventHandler(object sender, hello_wordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hello_wordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hello_wordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_EM_BUCompletedEventHandler(object sender, INS_EM_BUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_EM_BUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_EM_BUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SD_WBERCompletedEventHandler(object sender, SD_WBERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SD_WBERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SD_WBERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SD_STCKCompletedEventHandler(object sender, SD_STCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SD_STCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SD_STCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SD_TVDRCompletedEventHandler(object sender, SD_TVDRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SD_TVDRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SD_TVDRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_DC_CHECKCompletedEventHandler(object sender, INS_DC_CHECKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_DC_CHECKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_DC_CHECKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void QRY_DC_CHECKCompletedEventHandler(object sender, QRY_DC_CHECKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QRY_DC_CHECKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QRY_DC_CHECKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void QRY_EMP_IDCompletedEventHandler(object sender, QRY_EMP_IDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QRY_EMP_IDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QRY_EMP_IDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CHK_MES_ROUTECompletedEventHandler(object sender, CHK_MES_ROUTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CHK_MES_ROUTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CHK_MES_ROUTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_MES_STATIONCompletedEventHandler(object sender, INS_MES_STATIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_MES_STATIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_MES_STATIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_MES_PART_LINKCompletedEventHandler(object sender, INS_MES_PART_LINKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_MES_PART_LINKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_MES_PART_LINKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GET_DIXIE_MACCompletedEventHandler(object sender, GET_DIXIE_MACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_DIXIE_MACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_DIXIE_MACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UPD_DIXIE_MACCompletedEventHandler(object sender, UPD_DIXIE_MACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPD_DIXIE_MACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPD_DIXIE_MACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void QRY_sn_kppnCompletedEventHandler(object sender, QRY_sn_kppnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QRY_sn_kppnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QRY_sn_kppnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void get_8L_WOCompletedEventHandler(object sender, get_8L_WOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_8L_WOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_8L_WOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_check_3TCompletedEventHandler(object sender, INS_check_3TCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_check_3TCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_check_3TCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GET_ST_FILE_CONFIGCompletedEventHandler(object sender, GET_ST_FILE_CONFIGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_ST_FILE_CONFIGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_ST_FILE_CONFIGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_ST_FILECompletedEventHandler(object sender, INS_ST_FILECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_ST_FILECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_ST_FILECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_CHK_MOUSE_LABEL_RESULTCompletedEventHandler(object sender, INS_CHK_MOUSE_LABEL_RESULTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_CHK_MOUSE_LABEL_RESULTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_CHK_MOUSE_LABEL_RESULTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_AOI_PATHCompletedEventHandler(object sender, INS_AOI_PATHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_AOI_PATHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_AOI_PATHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_MV_TEST_LOGCompletedEventHandler(object sender, INS_MV_TEST_LOGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_MV_TEST_LOGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_MV_TEST_LOGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void INS_TEST_INFOCompletedEventHandler(object sender, INS_TEST_INFOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_TEST_INFOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_TEST_INFOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GET_TEST_INFOCompletedEventHandler(object sender, GET_TEST_INFOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_TEST_INFOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_TEST_INFOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591